#!/bin/bash

# Disable overscan
sudo sed -i "s/#disable_overscan=1/disable_overscan=1/" /boot/config.txt

# Set timezone
sudo ln -fs /usr/share/zoneinfo/Europe/Zurich /etc/localtime
sudo dpkg-reconfigure -f noninteractive tzdata

# Create udev rules file for Trezor
echo 'SUBSYSTEM=="usb", ATTR{idVendor}=="534c", ATTR{idProduct}=="0001", MODE="0666", GROUP="dialout", SYMLINK+="trezor%n"' | sudo tee /etc/udev/rules.d/51-trezor.rules > /dev/null
echo 'KERNEL=="hidraw*", ATTRS{idVendor}=="534c", ATTRS{idProduct}=="0001",  MODE="0666", GROUP="dialout"' | sudo tee -a /etc/udev/rules.d/51-trezor.rules > /dev/null

# Add panel items
cat ./panel-items-to-add >> ~/.config/lxpanel/LXDE-pi/panels/panel

# Update and upgrade
sudo apt-get update
sudo apt-get upgrade --assume-yes

# Set git credentials
git config --global user.email ""
git config --global user.name "Andreas Huber"

# Install printing support
sudo apt-get install cups --assume-yes
sudo usermod -a -G lpadmin pi

# Add printer
lpadmin -p Brother_HL-2240DW -v usb://Brother/HL-2270DW%20series?serial=C3N809081 -m gutenprint.5.2://hp-lj_2410/expert
lpadmin -p Brother_HL-2240DW -o PageSize=A4 
lpadmin -p Brother_HL-2240DW -o Resolution=600dpi 

# Install nodejs 6
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install nodejs --assume-yes

# Change locale and set memory split
sudo raspi-config
