#!/bin/bash

# Install Apache
sudo apt-get install apache2 --assume-yes
sudo systemctl start apache2
sudo systemctl enable apache2

# Install additional packages required by Owncloud
sudo apt-get install apache2 mariadb-server libapache2-mod-php7.0 php7.0-gd php7.0-json php7.0-mysql php7.0-curl php7.0-intl php7.0-mcrypt php-imagick php7.0-zip php7.0-xml php7.0-mbstring --assume-yes
