#!/bin/bash

# This script is based on https://www.avoiderrors.net/owncloud-10-raspberry-pi-3-raspbian-stretch/

# Install Apache
sudo apt-get install apache2 --assume-yes
sudo systemctl start apache2
sudo systemctl enable apache2

# Install additional packages required by Owncloud
sudo apt-get install apache2 mariadb-server libapache2-mod-php7.0 php7.0-gd php7.0-json php7.0-mysql php7.0-curl php7.0-intl php7.0-mcrypt php-imagick php7.0-zip php7.0-xml php7.0-mbstring --assume-yes

# Install ownCloud
wget https://download.owncloud.org/community/owncloud-10.0.4.tar.bz2
tar -xvf owncloud-10.0.4.tar.bz2
rm owncloud-10.0.4.tar.bz2
sudo chown -R www-data:www-data owncloud
sudo mv owncloud /var/www/html

# Configure apache
sudo cp ./owncloud.conf /etc/apache2/sites-available/
sudo ln -s /etc/apache2/sites-available/owncloud.conf /etc/apache2/sites-enabled/owncloud.conf
sudo a2enmod headers
sudo systemctl restart apache2
sudo a2enmod env
sudo a2enmod dir
sudo a2enmod mime

# Create mysql DB
sudo mysql -u "root" "-praspberry" < "create-db.sql"

# Configure owncloud
read -p "ownCloud admin username: " owncloud-admin-user
read -s -p "ownCloud admin password: " owncloud-admin-password

current-directory=$PWD
cd /var/www/html/owncloud/
sudo -u www-data php occ maintenance:install --database "mysql" --database-name "owncloud" --database-user "owncloud" --database-pass "12345" --admin-user "$owncloud-admin-user" --admin-pass "$owncloud-admin-password"
ip-address=$(hostname -I | tr -d '[:space:]')
sudo -u www-data php occ config:system:set trusted_domains 0 --value=$ip-address
cd $current-directory

xdg-open "http://$ip-address/owncloud"
