#!/bin/bash
set -o errexit
set -o nounset
set -o pipefail

# Update and upgrade
sudo apt-get update
sudo apt-get upgrade --assume-yes

# Enlarge swap file (enables hibernation)
sudo swapoff -a
sudo fallocate -l 16G /swapfile
sudo chmod 600 /swapfile
sudo mkswap /swapfile
sudo swapon /swapfile

# Install/uninstall software
# sudo apt-get remove firefox --assume-yes
# sudo apt-get install chromium-browser --assume-yes

# Power Settings
gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-timeout 3600
gsettings set org.gnome.settings-daemon.plugins.power power-button-action 'suspend'
gsettings set org.gnome.settings-daemon.plugins.power critical-battery-action 'hibernate'
gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-battery-timeout 1200
gsettings set org.gnome.settings-daemon.plugins.power percentage-critical 5

