#!/bin/bash
set -o errexit
set -o nounset
set -o pipefail

./../common/install-prerequisites

# Enlarge swap file to the amount of physical memory. Besides other benefits, this should enable hibernation.
# For some reason (probably drivers) hibernation does not work yet, but we'll do this anyway so that we can easily
# enable hibernation later.
sudo swapoff -a
sudo fallocate -l 16G /swapfile
sudo chmod 600 /swapfile
sudo mkswap /swapfile
sudo swapon /swapfile

# Enable hibernation in UI (uncomment this once hibernation works)
# cat enable-hibernation-in-ui.txt | sudo tee -a /etc/polkit-1/localauthority/50-local.d/com.ubuntu.enable-hibernate.pkla

# Power Settings
gsettings set org.gnome.desktop.session idle-delay 900
gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-timeout 3600
gsettings set org.gnome.settings-daemon.plugins.power power-button-action 'suspend'
# Uncomment this once hibernation works
# gsettings set org.gnome.settings-daemon.plugins.power critical-battery-action 'hibernate'
gsettings set org.gnome.settings-daemon.plugins.power percentage-critical 5
gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-battery-timeout 900

./../common/add-printer

# Uninstall Firefox, install Chromium
sudo apt-get remove firefox ubuntu-web-launchers --assume-yes
sudo apt-get install chromium-browser --assume-yes

./../common/reset-browser-preferences chromium-browser

# Install Visual Studio Code
# https://code.visualstudio.com/docs/setup/linux
wget -O vs-code.deb https://go.microsoft.com/fwlink/?LinkID=760868
sudo dpkg -i vs-code.deb
rm vs-code.deb

# Install Beyond Compare
# http://www.scootersoftware.com/download.php?zz=kb_linux_install
# https://askubuntu.com/questions/621351/gdebi-vs-dpkg-how-does-gdebi-automatically-gets-missing-dependancies-can-i-u
wget -O bcompare.deb https://www.scootersoftware.com/bcompare-4.2.4.22795_amd64.deb
sudo dpkg -i bcompare.deb
rm bcompare.deb
git config --global diff.tool bc3
git config --global difftool.bc3.trustExitCode true
git config --global merge.tool bc3
git config --global mergetool.bc3.trustExitCode true

# Install Chrome
wget -O chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo dpkg -i chrome.deb
rm chrome.deb

# Get missing dependencies for the packages installed with dpkg
sudo apt-get install -f --assume-yes

# This is not currently working 100% unattended, see comments in script for more information.
./../common/reset-browser-preferences google-chrome

# Install ownCloud
# https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client
echo "deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_17.10/ /" | sudo tee -a /etc/apt/sources.list.d/owncloud-client.list
wget -O ownCloud.key https://download.opensuse.org/repositories/isv:ownCloud:desktop/Ubuntu_17.10/Release.key
sudo apt-key add - < ownCloud.key
rm ownCloud.key
sudo apt-get update
sudo apt-get install owncloud-client
owncloud ~
