#!/bin/bash
# Assumes that setup2 will be executed after the reboot.
set -o errexit
set -o nounset
set -o pipefail

# Update and upgrade
sudo apt-get update
sudo apt-get upgrade --assume-yes

# Re-enable secure boot
sudo update-secureboot-policy --enable
sudo reboot
