#!/bin/bash
# Assumes that setup1 has been executed successfully.
set -o errexit
set -o nounset
set -o pipefail

./../common/init-git
./../common/install-prerequisites

# Enlarge swap file to the amount of physical memory.
sudo swapoff -a
sudo fallocate -l 16G /swapfile
sudo chmod 600 /swapfile
sudo mkswap /swapfile
sudo swapon /swapfile

# Hibernation does not work yet. It is probably due to the fact that Ubuntu requires a swap partition rather than a swap
# file for hibernation. It appears that setting up an encrypted swap partition is currently too complicated. The stock
# installer seems to allow it but then crashes. Setting it up after installation requires booting into a live
# environment, which seems too much hassle, given that the next version of Ubuntu might support it out of the box.

# Enable hibernation in UI (uncomment this once hibernation works)
# cat enable-hibernation-in-ui.txt | sudo tee -a /etc/polkit-1/localauthority/50-local.d/com.ubuntu.enable-hibernate.pkla

# Power Settings
gsettings set org.gnome.desktop.session idle-delay 900
gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-battery-type 'suspend'
gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-battery-timeout 900
gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type 'suspend'
gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-timeout 3600
gsettings set org.gnome.settings-daemon.plugins.power power-button-action 'suspend'
gsettings set org.gnome.settings-daemon.plugins.power percentage-critical 5
# Uncomment this once hibernation works
# gsettings set org.gnome.settings-daemon.plugins.power critical-battery-action 'hibernate'

./../common/add-printer
./../common/install-nodejs

# Install Java Runtime Environment
sudo apt-get install default-jre --assume-yes

# Uninstall Firefox, install Chromium
sudo apt-get remove firefox ubuntu-web-launchers --assume-yes
sudo apt-get install chromium-browser --assume-yes

./../common/reset-browser-preferences chromium-browser

# Create udev rules file for Trezor
# http://doc.satoshilabs.com/trezor-user/settingupchromeonlinux.html
sudo cp 51-trezor.rules /etc/udev/rules.d

# Install Trezor Bridge
wget -O trezor-bridge.deb https://wallet.trezor.io/data/bridge/2.0.7/trezor-bridge_2.0.7_amd64.deb
sudo dpkg -i --force-depends trezor-bridge.deb
rm trezor-bridge.deb

# Install Visual Studio Code
# https://code.visualstudio.com/docs/setup/linux
wget -O vs-code.deb https://go.microsoft.com/fwlink/?LinkID=760868
sudo dpkg -i --force-depends vs-code.deb
rm vs-code.deb

# Install Beyond Compare
# http://www.scootersoftware.com/download.php?zz=kb_linux_install
# https://askubuntu.com/questions/621351/gdebi-vs-dpkg-how-does-gdebi-automatically-gets-missing-dependancies-can-i-u
wget -O bcompare.deb https://www.scootersoftware.com/bcompare-4.2.4.22795_amd64.deb
sudo dpkg -i --force-depends bcompare.deb
rm bcompare.deb
git config --global diff.tool bc3
git config --global difftool.bc3.trustExitCode true
git config --global merge.tool bc3
git config --global mergetool.bc3.trustExitCode true

# Install Chrome
wget -O chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo dpkg -i --force-depends chrome.deb
rm chrome.deb

# Get missing dependencies for the packages installed with dpkg
sudo apt-get install -f --assume-yes

# This is not currently working 100% unattended, see comments in script for more information.
./../common/reset-browser-preferences google-chrome

# Install ownCloud
# https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client
echo "deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_17.10/ /" | sudo tee -a /etc/apt/sources.list.d/owncloud-client.list
wget -O ownCloud.key https://download.opensuse.org/repositories/isv:ownCloud:desktop/Ubuntu_17.10/Release.key
sudo apt-key add - < ownCloud.key
rm ownCloud.key
sudo apt-get update
sudo apt-get install owncloud-client --assume-yes
owncloud &

# Install Raccoon
sudo mkdir /opt/Raccoon
sudo wget -O /opt/Raccoon/raccoon.jar http://raccoon.onyxbits.de/sites/raccoon.onyxbits.de/files/raccoon-4.2.1.jar
sudo chmod u+x /opt/Raccoon/raccoon.jar