#!/bin/bash
set -o errexit
set -o nounset
set -o pipefail

./../common/install-prerequisites

# Enlarge swap file to the amount of physical memory. Besides other benefits, this should enable hibernation.
# For some reason (probably drivers) hibernation does not work yet, but we'll do this anyway so that we can easily
# enable hibernation later.
sudo swapoff -a
sudo fallocate -l 16G /swapfile
sudo chmod 600 /swapfile
sudo mkswap /swapfile
sudo swapon /swapfile

# Enable hibernation in UI (uncomment this once hibernation works)
# cat enable-hibernation-in-ui.txt | sudo tee -a /etc/polkit-1/localauthority/50-local.d/com.ubuntu.enable-hibernate.pkla

# Power Settings
gsettings set org.gnome.desktop.session idle-delay 600
gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-timeout 3600
gsettings set org.gnome.settings-daemon.plugins.power power-button-action 'suspend'
# Uncomment this once hibernation works
# gsettings set org.gnome.settings-daemon.plugins.power critical-battery-action 'hibernate'
gsettings set org.gnome.settings-daemon.plugins.power percentage-critical 5
gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-battery-timeout 900

./../common/add-printer

# Uninstall Firefox, install Chromium
sudo apt-get remove firefox ubuntu-web-launchers --assume-yes
sudo apt-get install chromium-browser --assume-yes

./../common/reset-browser-preferences

# Install Visual Studio Code
wget -O vs-code.deb https://go.microsoft.com/fwlink/?LinkID=760868
sudo dpkg -i vs-code.deb
rm vs-code.deb

# Install Beyond Compare
wget -O bcompare.deb https://www.scootersoftware.com/bcompare-4.2.4.22795_amd64.deb
sudo dpkg -i bcompare.deb
rm bcompare.deb

# Get missing dependencies for the packages installed with dpkg
sudo apt-get install -f --assume-yes

