#!/bin/bash
set -o errexit
set -o nounset
set -o pipefail

# Set timezone
sudo raspi-config nonint do_change_timezone Europe/Zurich 

# Update and upgrade
sudo apt-get update
sudo apt-get upgrade --assume-yes

# Install write support for NTFS (necessary if you want to write to a memory stick on Windows and Raspbian)
sudo apt-get install ntfs-3g --assume-yes

# Install printing support
sudo apt-get install cups --assume-yes
sudo usermod -a -G lpadmin pi

# Add printer
lpadmin -p Brother_HL-2240DW -v usb://Brother/HL-2270DW%20series?serial=C3N809081 -m gutenprint.5.2://hp-lj_2410/expert
lpadmin -p Brother_HL-2240DW -o PageSize=A4 
lpadmin -p Brother_HL-2240DW -o Resolution=600dpi 

# Install nodejs 6
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install nodejs --assume-yes

# Create udev rules file for Trezor
# http://doc.satoshilabs.com/trezor-user/settingupchromeonlinux.html
sudo cp 51-trezor.rules /etc/udev/rules.d

# Add panel items (displayed in the top right corner)
# Raspbian Lite doesn't have them so check if file exists first
if [ -f "~/.config/lxpanel/LXDE-pi/panels/panel" ]; then
  cat ./panel-items-to-add >> ~/.config/lxpanel/LXDE-pi/panels/panel
fi

# Set options that require reboot
sudo raspi-config nonint do_change_locale en_US.UTF-8
sudo raspi-config nonint do_overscan 1
sudo raspi-config nonint do_memory_split 32
reboot