#!/bin/bash
# NOTE: Depends on the cups package.
set -o errexit
set -o nounset
set -o pipefail

# Direct web browser to http://localhost:631 for administration 
lpadmin -p Brother_HL-2270DW -E -v dnssd://Brother%20HL-2270DW%20series._pdl-datastream._tcp.local/ -m gutenprint.5.2://brother-hl-2250dn/expert
lpadmin -p Brother_HL-2270DW -o PageSize=A4
lpadmin -p Brother_HL-2270DW -o Resolution=600dpi
lpadmin -p Brother_HL-2270DW -o Duplex=DuplexNoTumble
lpoptions -d Brother_HL-2270DW
