#!/bin/bash
# NOTE: Depends on the git package.
set -o errexit
set -o nounset
set -o pipefail

git config --global user.name "Andreas Huber Dönni"
git config --global user.email andreashuber69@users.noreply.github.com
git config --global credential.helper 'cache --timeout 86400'