#!/bin/bash
set -o errexit
set -o nounset
set -o pipefail

# Install wmctrl (close applications from the command line), sqlite3, jq (command line JSON parser/editor)
sudo apt-get install wmctrl sqlite3 jq --assume-yes
