#!/bin/bash
# This script is based on https://doc.owncloud.org/server/9.0/admin_manual/maintenance/backup.html
set -o errexit
set -o nounset
set -o pipefail

current_datetime=$(date +"%Y%m%d_%H%M%S")
mkdir /media/pi/Backup/$current_datetime
sudo tar acf /media/pi/Backup/$current_datetime/files.tar.gz /var/www/html/owncloud/config /var/www/html/owncloud/data
mysqldump --single-transaction -h localhost -u owncloud -p12345 owncloud > /media/pi/Backup/$current_datetime/db.bak