#!/bin/bash

# This script is based on https://doc.owncloud.org/server/9.0/admin_manual/maintenance/backup.html

current_datetime=$(date +"%Y%m%d_%H%M%S")
sudo rsync -Aax /var/www/html/owncloud/config /var/www/html/owncloud/data /media/pi/Backup/$current_datetime/
mysqldump --single-transaction -h localhost -u owncloud -p12345 owncloud > /media/pi/Backup/$current_datetime/db.bak