#!/bin/bash

# This script is based on https://doc.owncloud.org/server/9.0/admin_manual/maintenance/restore.html

sudo rm -r /var/www/html/owncloud/config
sudo rm -r /var/www/html/owncloud/data
sudo tar xzpvf $1/files.tar.gz -C /
mysql -h localhost -u owncloud -p12345 owncloud < $1/db.bak
