#!/bin/bash
set -o errexit
set -o nounset
set -o pipefail

# Set timezone
sudo raspi-config nonint do_change_timezone Europe/Zurich 

# Update and upgrade
sudo apt-get update
sudo apt-get upgrade --assume-yes

# Install support for exFAT (necessary if you want to mount a memory stick on Windows and Raspbian)
sudo apt-get install exfat-fuse exfat-utils --assume-yes

# Install printing support
# Direct web browser to http://localhost:631 for further administration 
sudo apt-get install cups --assume-yes
sudo usermod -a -G lpadmin pi

# Add printer
lpadmin -p Brother_HL-2270DW -E -v usb://Brother/HL-2270DW%20series?serial=C3N809081 -m gutenprint.5.2://hp-lj_2410/expert
lpadmin -p Brother_HL-2270DW -o PageSize=A4
lpadmin -p Brother_HL-2270DW -o Resolution=600dpi
lpadmin -p Brother_HL-2270DW -o Duplex=DuplexNoTumble
lpoptions -d Brother_HL-2270DW

# Install nodejs 6
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install nodejs --assume-yes

# Create udev rules file for Trezor
# http://doc.satoshilabs.com/trezor-user/settingupchromeonlinux.html
sudo cp 51-trezor.rules /etc/udev/rules.d

# Add panel items (displayed in the top right corner)
cat ./panel-items-to-add >> ~/.config/lxpanel/LXDE-pi/panels/panel

# Set options that require reboot
sudo raspi-config nonint do_overscan 1

git clone https://github.com/andreashuber69/owncloud ../../owncloud
./../../owncloud/setup1
