#!/bin/bash
set -o errexit
set -o nounset
set -o pipefail

# Set timezone
sudo raspi-config nonint do_change_timezone Europe/Zurich 

# Update and upgrade
sudo apt-get update
sudo apt-get upgrade --assume-yes

./../common/init-git
./../common/install-prerequisites

# Install printing support
sudo apt-get install cups --assume-yes
sudo usermod -a -G lpadmin pi

./../common/add-printer
./../common/install-nodejs
./../common/reset-browser-preferences chromium-browser

# Create udev rules file for Trezor
# http://doc.satoshilabs.com/trezor-user/settingupchromeonlinux.html
sudo cp 51-trezor.rules /etc/udev/rules.d

# Add panel items (displayed in the top right corner)
cat ./panel-items-to-add >> ~/.config/lxpanel/LXDE-pi/panels/panel

# Set options that require reboot
sudo raspi-config nonint do_overscan 1

git clone https://github.com/andreashuber69/owncloud ../../owncloud
./../../owncloud/setup1
