#!/bin/bash
# Based on https://doc.owncloud.org/server/9.0/admin_manual/maintenance/restore.html
# Expects as the only argument a path to a folder created by ./backup
# This will restore a fresh installation of ownCloud to the state when ./backup was executed
set -o errexit
set -o nounset
set -o pipefail

sudo rm -r /var/www/html/owncloud/config
sudo rm -r /var/www/html/owncloud/data
sudo tar xzpvf $1/files.tar.gz -C /
mysql -h localhost -u owncloud -p12345 owncloud < $1/db.bak
